### ISSUE TITLE
I wrote a pretty lengthy response to you reddit thred, but it was closed before i could send it

### ISSUE THREAD

**Issue by anttipekka** [celso-na-teixeira/cart-managment#1]
I wrote a long reply to your reddit thread but it got closed before i managed to send it, so i'll write some comments here so you might notice them. @celso-na-teixeira 

Have you actually run the tests? I'd guess they should all fail as they are written. 

When you're using mocks you can't really do stuff like. 

```
ItemEntity itemEntity = new ItemEntity("Queijo", "Queijo dos Açores", 10.5, 1);
    cartRepository.save(itemEntity);
    ItemEntity i = new ItemEntity();
    when(cartRepository.findById(1L)).thenReturn(Optional.of(i));
    List<Item> items = cartService.getItems();
    cartService.removeItem(1L);
    ItemEntity deletedItemEntity = cartRepository.findById(1L).orElse(null);
    assertNull(deletedItemEntity);
```

Your cartRepository is a mock, when you do a save on it it doesn't actually get saved anywhere. It just calls the mock''s method. So when you do ItemEntity deletedItemEntity = cartRepository.findById(1L).orElse(null); it will never find anything. 

Same in most of the tests. 
Let's try to write testAddItem function like it should be written when using mocks

Let's starty by fixing your setup. You declare your itemMapper as a mock but then overwrite it in your setup method by initializing it. so let's skip that. 

```
@Before
  public void setUp(){
    MockitoAnnotations.openMocks(this);
    cartService = new CartServiceImpl(cartRepository, itemMapper);
  }
```

So now we'll use actual mock itemMapper instead of what you initialized there. 

``` 
@Test
  public void testAddItem(){
    Item item = new Item("Vinho", "Vinho do Douro", 3.99, 2);
    ItemEntity itemEntity = itemMapper.toEntity(item);
    when(cartRepository.findById(1L)).thenReturn(Optional.empty());
    when(cartRepository.save(itemEntity)).thenReturn(itemEntity);
    cartService.addItem(item);
    verify(cartRepository).save(itemEntity);
  }
```

This is your initial implementation of testAddItem method, there are several issues. When you look at your service implementation of the method

```
@Override
  public void addItem(final Item item) throws CartException {
    logger.info("Adding item.");
    try{
      ItemEntity itemEntity = itemMapper.toEntity(item);
      cartRepository.save(itemEntity);
    }catch (DataAccessException exception){
      logger.error("Failed to add item to cart.", exception);
      throw new CartException("Unable to add item to cart. Please try again later.");
    }catch (Exception exception){
      logger.error("Unexpected error while adding item to cart.", exception);
      throw new CartException("An unexpected error occurred. Please try again later.");
    }
  }
```

cartRepository.findById(1L) is never called in there. Neither is cartRepository.findById(1L)

So these to basically nothing when(cartRepository.findById(1L)).thenReturn(Optional.empty());

Let's see how this should be written if using the mocks. 
```
@Test
  public void testAddItem(){
    Item item = new Item("Vinho", "Vinho do Douro", 3.99, 2);
    ItemEntity itemEntity = new ItemEntity();
    when(itemMapper.toEntity(item)).thenReturn(itemEntity);
    cartService.addItem(item);
    verify(cartRepository).save(itemEntity);
  }
```

Your service implementation calls itemMapper.toEntity(item), so since we are using itemMapper mock you should mock that call `when(itemMapper.toEntity(item)).thenReturn(itemEntity);`
 
Now we are telling that when code calls itemMapper.toEntity with specified item value then we return itemEntity specified in the test. Now we can actually verify that cartRepository.save is called with that itemEntity

All that being said, i think this is a use case where you should actually use mostly integration tests, instead of unit tests. In the example i gave how your addItem can be tested with mocks, we are mostly testing that our mocks work, instead of testing that the add item method actually works. Unit tests are great and have their place in testing logic, but in this case they provide limited value since they don't actually test that the method works.

**Comment by celso-na-teixeira** [comment]
Hi @anttipekka ,

Thank you so much for reaching out to me on Git and for your assistance. I sincerely appreciate it.

I have implemented several changes to the service method, and I will make the changes you suggest to the tests. Moreover, I am also planning to create integration tests to better understand how it works and the difference between integration tests and unit tests.

As mentioned in my Reddit post, I don't have extensive experience with testing. However, I am actively working on improving my skills in this area and dedicating myself to self-improvement.

Once again, I cannot thank you enough for your invaluable support.

Cheers!
